import {
  ActivityItem,
  AlertItem,
  Campaign,
  KpiMetric,
  NavItem,
  Product,
  TrafficPoint,
} from './models';

export const NAV_ITEMS: NavItem[] = [
  { label: 'Dashboard', route: '/dashboard', icon: 'grid' },
  { label: 'Campaigns', route: '/campaigns', icon: 'megaphone' },
  { label: 'Products', route: '/products', icon: 'box' },
  { label: 'Reports', route: '/reports', icon: 'bar-chart' },
  { label: 'Settings', route: '/settings', icon: 'settings' },
];

export const KPI_METRICS: KpiMetric[] = [
  {
    id: 'revenue',
    label: 'Revenue',
    value: '$128,450',
    trend: 12.4,
    trendLabel: 'vs last month',
    icon: 'dollar-sign',
  },
  {
    id: 'orders',
    label: 'Orders',
    value: '3,284',
    trend: 4.1,
    trendLabel: 'vs last month',
    icon: 'shopping-cart',
  },
  {
    id: 'conversion',
    label: 'Conversion Rate',
    value: '3.62%',
    trend: -0.8,
    trendLabel: 'vs last month',
    icon: 'target',
  },
  {
    id: 'campaigns',
    label: 'Active Campaigns',
    value: '18',
    trend: 2,
    trendLabel: 'new this month',
    icon: 'megaphone',
  },
];

export const CAMPAIGNS: Campaign[] = [
  {
    id: 'c-1',
    name: 'Q3 Brand Awareness Push',
    channel: 'Search',
    status: 'active',
    spend: 8240,
    revenue: 24680,
    updated: '2026-09-16',
  },
  {
    id: 'c-2',
    name: 'Back to School',
    channel: 'Social',
    status: 'active',
    spend: 5120,
    revenue: 18990,
    updated: '2026-09-15',
  },
  {
    id: 'c-3',
    name: 'Holiday Retargeting Campaign for Returning Customers',
    channel: 'Display',
    status: 'paused',
    spend: 12480,
    revenue: 9870,
    updated: '2026-09-14',
  },
  {
    id: 'c-4',
    name: 'Flash Sale',
    channel: 'Email',
    status: 'ended',
    spend: 1240,
    revenue: 6100,
    updated: '2026-09-10',
  },
  {
    id: 'c-5',
    name: 'New Product Launch: Aurora Series',
    channel: 'Search',
    status: 'active',
    spend: 15600,
    revenue: 42300,
    updated: '2026-09-16',
  },
  {
    id: 'c-6',
    name: 'Winback',
    channel: 'Email',
    status: 'draft',
    spend: 0,
    revenue: 0,
    updated: '2026-09-12',
  },
  {
    id: 'c-7',
    name: 'Competitor Conquest Search Terms',
    channel: 'Search',
    status: 'active',
    spend: 9310,
    revenue: 15420,
    updated: '2026-09-13',
  },
  {
    id: 'c-8',
    name: 'App Install Push',
    channel: 'Social',
    status: 'paused',
    spend: 4200,
    revenue: 3900,
    updated: '2026-09-11',
  },
  {
    id: 'c-9',
    name: 'Loyalty Program Reminder',
    channel: 'Email',
    status: 'active',
    spend: 980,
    revenue: 5230,
    updated: '2026-09-16',
  },
  {
    id: 'c-10',
    name: 'International Expansion: DACH Region',
    channel: 'Display',
    status: 'active',
    spend: 18900,
    revenue: 21100,
    updated: '2026-09-09',
  },
  {
    id: 'c-11',
    name: 'Weekend Flash Promo',
    channel: 'Social',
    status: 'ended',
    spend: 2100,
    revenue: 4650,
    updated: '2026-09-08',
  },
  {
    id: 'c-12',
    name: 'Enterprise ABM Sequence',
    channel: 'Email',
    status: 'active',
    spend: 3300,
    revenue: 27800,
    updated: '2026-09-15',
  },
  {
    id: 'c-13',
    name: 'Video Views',
    channel: 'Social',
    status: 'draft',
    spend: 0,
    revenue: 0,
    updated: '2026-09-05',
  },
  {
    id: 'c-14',
    name: 'Search Brand Defense Terms',
    channel: 'Search',
    status: 'active',
    spend: 6700,
    revenue: 31200,
    updated: '2026-09-16',
  },
];

export const PRODUCTS: Product[] = [
  { id: 'p-1', name: 'Aurora Wireless Headphones', sku: 'AUR-100', category: 'Audio', price: 129.0, unitsSold: 842, stock: 210 },
  { id: 'p-2', name: 'Nimbus Standing Desk', sku: 'NIM-220', category: 'Furniture', price: 449.0, unitsSold: 156, stock: 34 },
  { id: 'p-3', name: 'Pulse Fitness Tracker', sku: 'PLS-050', category: 'Wearables', price: 79.0, unitsSold: 1290, stock: 480 },
  { id: 'p-4', name: 'Ember Ceramic Mug Set', sku: 'EMB-014', category: 'Home', price: 34.0, unitsSold: 2110, stock: 900 },
  { id: 'p-5', name: 'Vector Mechanical Keyboard', sku: 'VEC-330', category: 'Accessories', price: 159.0, unitsSold: 512, stock: 120 },
  { id: 'p-6', name: 'Halo Smart Lamp', sku: 'HAL-075', category: 'Home', price: 59.0, unitsSold: 733, stock: 260 },
];

export const ACTIVITY: ActivityItem[] = [
  { id: 'a-1', actor: 'Dana Kim', action: 'launched', target: 'New Product Launch: Aurora Series', timestamp: '10 min ago' },
  { id: 'a-2', actor: 'System', action: 'paused', target: 'Holiday Retargeting Campaign', timestamp: '42 min ago' },
  { id: 'a-3', actor: 'Marcus Webb', action: 'updated budget for', target: 'Competitor Conquest Search Terms', timestamp: '1 hr ago' },
  { id: 'a-4', actor: 'Priya Nair', action: 'created', target: 'Winback', timestamp: '3 hrs ago' },
  { id: 'a-5', actor: 'System', action: 'flagged low ROAS on', target: 'App Install Push', timestamp: '5 hrs ago' },
  { id: 'a-6', actor: 'Dana Kim', action: 'archived', target: 'Weekend Flash Promo', timestamp: 'Yesterday' },
];

export const ALERTS: AlertItem[] = [
  { id: 'al-1', severity: 'critical', message: 'App Install Push ROAS dropped below 1.0', timestamp: '5 hrs ago' },
  { id: 'al-2', severity: 'warning', message: 'Holiday Retargeting Campaign spend nearing budget cap', timestamp: 'Yesterday' },
  { id: 'al-3', severity: 'info', message: '3 draft campaigns ready for review', timestamp: '2 days ago' },
];

export const TRAFFIC_SERIES: TrafficPoint[] = [
  { label: 'Mon', visits: 4200, revenue: 12400 },
  { label: 'Tue', visits: 4800, revenue: 14100 },
  { label: 'Wed', visits: 4500, revenue: 13200 },
  { label: 'Thu', visits: 5600, revenue: 17800 },
  { label: 'Fri', visits: 6100, revenue: 19900 },
  { label: 'Sat', visits: 5200, revenue: 16200 },
  { label: 'Sun', visits: 4700, revenue: 14900 },
];
